# This script is used to process images and stitch the tiles. 
# It parses the xml files that are generated by Zeiss Zen Blue software while taking images. 
# The relative positions of the tiles are read. 
# If the relative positions are specified in other ways, one can use 
# function stitchShiftTiles(tileIDs,tileX,tileY,nx,ny) in NeuTu.py
# Usage
#	python stitchTilesZeissXNL.py dataDir
#

import sys, os

# check number of inputs. 
if (len(sys.argv) < 2 or len(sys.argv) > 2):
	print "This script requires one arguments. Usage: python stitchTilesZeissXML.py dirData"
	sys.exit(0)

dataDir = sys.argv[1]

print 'The data directory is ', dataDir

# change directory to dataDir
currentDir = os.getcwd()
os.chdir(dataDir)

import ShuTu

# stitch tiles
ShuTu.xmlStitchImages()

# get back to the original directory
os.chdir(currentDir)

